name: branch

on:
  push:
    branches-ignore: [main, gh-pages]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: wtnb75/actions/python@main
      with:
        pipinstall: ".[dev]"
    - uses: wtnb75/actions/flake8@main
    - uses: wtnb75/actions/pytest@main
    - uses: wtnb75/actions/wheel@main
    - uses: wtnb75/actions/merge-pages@dollar
      with:
        dirs: cover
        pydist: dist
    - uses: wtnb75/actions/docker@main
      with:
        password: ${{ secrets.GITHUB_TOKEN }}
        context: ./docker
