name: tag

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: versioning
      run: "echo \"VERSION = '${GITHUB_REF##*/v}'\" > editrest/version.py"
    - uses: wtnb75/actions/python@main
      with:
        pipinstall: ".[dev]"
    - uses: wtnb75/actions/flake8@main
    - uses: wtnb75/actions/pytest@main
    - id: wheel
      uses: wtnb75/actions/wheel@main
    - uses: wtnb75/actions/docker@main
      with:
        push: 'true'
        password: ${{ secrets.GITHUB_TOKEN }}
        context: ./docker
        image-version: ${{ github.ref_name }}
        build-args: |
          GH_BRANCH=${{ github.ref_name }}
    - uses: wtnb75/actions/pypi-upload@main
      with:
        username: ${{ secrets.TWINE_USERNAME }}
        password: ${{ secrets.TWINE_PASSWORD }}
        file: dist/${{ steps.wheel.outputs.filename }}
